application:
  appId: <<IO_ASSET_ID>>
  assetId: <<IO_ASSET_ID>>
  sdlcType: EDM
  appType: Webapp
  webservice: true
  restApi: true
  microservice: false
  projectLanguage: Java
  platformVersion: Java 8
  buildSystem: Maven
  riskMatrixRevision: Rev1.0
  sourceFilePattern: .*\\+\\+\\+.*(\\.java|\\.jsp)+.*
  sensitivePackagePattern: .*(\\+\\+\\+.*(com\\/synopsys\\/app)).*
  fileChangeThreshold: 20
  release: major
environment:
  scm: github
  scmOwner: <<GITHUB_OWNER_NAME>>
  scmRepositoryName: <<GITHUB_REPO_NAME>>
  scmBranchName: master
  bitbucketUserName: <<BITBUCKET_USERNAME>>
  bitbucketPassword: <<BITBUCKET_PASSWORD>>
  bitbucketApiUrl: https://api.bitbucket.org/2.0/repositories/
  githubApiUrl: https://api.github.com/repos/
  jiraProjectName: <<JIRA_PROJECT_NAME>>
  jiraIssuesQuery: <<JIRA_ISSUES_QUERY>>
  jiraApiUrl: <<JIRA_API_URL>>
  jiraUserName: <<JIRA_USERNAME>>
  jiraAuthToken: <<JIRA_AUTH_TOKEN>>
